spring:
  # application:
  #   name: iron1000106
  # profiles:
  #   active: dev
  # cloud:
  #   config:
  #     name: common,spring,logging,ora11g,iron
  #     profile: dev
  #     uri: ${PEIZHI_URL:http://mes106.mti.avic.com/peizhi}
  output:
    ansi:
      enabled: always
  datasource:
    platform: mysql
    username: root
    password: root
    url: jdbc:mysql://minix.jeanhwea.io:3306/database?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 9090
